name: Update badges

on:
  workflow_dispatch:
  schedule:
    # Runs at at midnight every Friday
    - cron: "0 0 * * FRI"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: "moruf-ajibike"
